# Generated by Django 5.0.1 on 2024-11-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unregisteredorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('pain', 'Paid')], default='ordered', max_length=10),
        ),
    ]
